# -*- coding: utf-8 -*-
"""fd2.0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bxZEw_K713qvqiQn_9gId4kmZDhSm687
"""

import numpy
import cv2
from google.colab.patches import cv2_imshow

!pwd

face_cascade = cv2.CascadeClassifier("/content/haarcascade_frontalface_default.xml")
image = cv2.imread("/content/kids.jpeg")
image = cv2.resize(image, (800,533))
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

print(type(gray_image))

faces=face_cascade.detectMultiScale(gray_image,scaleFactor=1.10,minNeighbors=5)
for x,y,w,h in faces:
    image=cv2.rectangle(image, (x,y), (x+w, y+h), (0, 255, 0),1)
    cv2_imshow(image)
    k=cv2.waitKey(2000)
cv2.destroyAllWindows()